application:
  logging:
    enabled: true
    level: WARN
    printArgs: true
  recover:
    enabled: true
    noRecoverFor:
    - ArithmeticException.class
server:
  port: 8080
spring:
  application:
    name: timesheet-rest
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  jpa:
#    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    enabled: false
  instance:
    preferIpAddress: true
